# Generated by Django 4.1 on 2022-08-05 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Task_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('priority', models.SmallIntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(default='2022-08-05', help_text='beginning of the task')),
                ('date_target', models.DateField(default='2022-08-05', help_text='date of next report')),
                ('status', models.CharField(help_text=' comment to current Task status', max_length=120)),
                ('active', models.BooleanField(default=True, help_text='False if the Task closed')),
                ('date_finish', models.DateField(blank=True, help_text='date of closing task', null=True)),
                ('finish_reason', models.CharField(help_text='fulfilled or reason why rejected', max_length=120)),
                ('current_date', models.DateField(default='2022-08-05', help_text='last report date')),
                ('name', models.CharField(help_text='Task name', max_length=240)),
                ('priority', models.SmallIntegerField(default=100, help_text='from 1 to 100 priority of task')),
                ('overal_priority', models.DecimalField(decimal_places=2, default=100.0, help_text='asks.priority*Task_type.prority/100', max_digits=6)),
                ('to_do_first', models.CharField(help_text='first step for solving', max_length=240)),
                ('to_do_second', models.CharField(help_text='next step for solving', max_length=240)),
                ('notes', models.CharField(help_text='additional information', max_length=240)),
                ('income_affect', models.BooleanField(default=False, help_text='if affects on income')),
                ('income_monthly_effect', models.FloatField(default=0, help_text='monthly income change')),
                ('expenses_affect', models.BooleanField(default=False, help_text='if affects on expenses')),
                ('expenses_monthly_effect', models.FloatField(default=0, help_text='monthly expenses change')),
                ('profit_affect', models.BooleanField(default=False, help_text='if affects on profit')),
                ('profit_monthly_effect', models.FloatField(default=0, help_text='monthly profit change')),
                ('other_effect', models.CharField(blank=True, help_text='if affects other busyness processes', max_length=240)),
                ('investments', models.FloatField(default=0, help_text='investments amount in thsnds')),
                ('investments_start', models.DateField(blank=True, help_text='date of first payment', null=True)),
                ('investments_period', models.IntegerField(default=0, help_text='in months')),
                ('monthly_expenses', models.FloatField(default=0, help_text='monthly costs in thsnds')),
                ('expenses_start', models.DateField(blank=True, help_text='date of first payment', null=True)),
                ('expenses_period', models.IntegerField(default=0, help_text='period in months')),
                ('last_report_summary', models.CharField(default='отчет', help_text='last report summary', max_length=120)),
                ('last_report_file', models.FileField(blank=True, help_text='last report for current task', null=True, upload_to='')),
                ('last_log', models.CharField(help_text='summary of last changes', max_length=240)),
                ('person', models.ForeignKey(blank=True, help_text='current responsible person', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gendir.persons')),
                ('position', models.ForeignKey(blank=True, help_text='normal position for responsible person', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gendir.positions')),
                ('type', models.ForeignKey(help_text='Task type', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gendir.task_types')),
            ],
        ),
        migrations.CreateModel(
            name='Tasks_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField(default='2022-08-05', help_text='when task changed')),
                ('date_start', models.DateField(default='2022-08-05', help_text='beginning of the task')),
                ('date_target', models.DateField(default='2022-08-05', help_text='date of next report')),
                ('status', models.CharField(help_text=' comment to current Task status', max_length=120)),
                ('active', models.BooleanField(default=True, help_text='False if the Task closed')),
                ('date_finish', models.DateField(blank=True, help_text='date of closing task', null=True)),
                ('finish_reason', models.CharField(help_text='fulfilled or reason why rejected', max_length=120)),
                ('current_date', models.DateField(default='2022-08-05', help_text='last report date')),
                ('name', models.CharField(help_text='Task name', max_length=240)),
                ('priority', models.SmallIntegerField(default=100, help_text='from 1 to 100 priority of task')),
                ('overal_priority', models.DecimalField(decimal_places=2, default=100.0, help_text='asks.priority*Task_type.prority/100', max_digits=6)),
                ('to_do_first', models.CharField(help_text='first step for solving', max_length=240)),
                ('to_do_second', models.CharField(help_text='next step for solving', max_length=240)),
                ('notes', models.CharField(help_text='additional information', max_length=240)),
                ('income_affect', models.BooleanField(default=False, help_text='if affects on income')),
                ('income_monthly_effect', models.FloatField(default=0, help_text='monthly income change')),
                ('expenses_affect', models.BooleanField(default=False, help_text='if affects on expenses')),
                ('expenses_monthly_effect', models.FloatField(default=0, help_text='monthly expenses change')),
                ('profit_affect', models.BooleanField(default=False, help_text='if affects on profit')),
                ('profit_monthly_effect', models.FloatField(default=0, help_text='monthly profit change')),
                ('other_effect', models.CharField(blank=True, help_text='if affects other busyness processes', max_length=240)),
                ('investments', models.FloatField(default=0, help_text='investments amount in thsnds')),
                ('investments_start', models.DateField(blank=True, help_text='date of first payment', null=True)),
                ('investments_period', models.IntegerField(default=0, help_text='in months')),
                ('monthly_expenses', models.FloatField(default=0, help_text='monthly costs in thsnds')),
                ('expenses_start', models.DateField(blank=True, help_text='date of first payment', null=True)),
                ('expenses_period', models.IntegerField(default=0, help_text='period in months')),
                ('last_report_summary', models.CharField(default='отчет', help_text='last report summary', max_length=120)),
                ('last_report_file', models.FileField(blank=True, help_text='last report for current task', null=True, upload_to='')),
                ('last_log', models.CharField(help_text='summary of last changes', max_length=240)),
                ('log_person', models.ForeignKey(blank=True, help_text='who made changes', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_person', to='gendir.persons')),
                ('person', models.ForeignKey(blank=True, help_text='current responsible person', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gendir.persons')),
                ('position', models.ForeignKey(blank=True, help_text='normal position for responsible person', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_person', to='gendir.positions')),
                ('task', models.ForeignKey(help_text='what task changed', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gendir.tasks')),
                ('type', models.ForeignKey(help_text='Task type', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gendir.task_types')),
            ],
        ),
        migrations.AddField(
            model_name='persons',
            name='main_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gendir.positions'),
        ),
    ]
