# Generated by Django 4.1 on 2022-08-08 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gendir', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='task_id',
            field=models.SmallIntegerField(default=0, help_text='task id'),
        ),
    ]
