# Generated by Django 4.1 on 2022-08-08 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gendir', '0002_tasks_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='log_date',
            field=models.DateField(default='2022-08-05', help_text='when task changed'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='log_person',
            field=models.ForeignKey(blank=True, help_text='who made changes', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Tasks_Log',
        ),
    ]
